version: "3.4"

services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      ODH_URL: ${ODH_URL}
      ODH_AUTH_URL: ${ODH_AUTH_URL}
      ODH_AUTH_CLIENT_ID: ${ODH_AUTH_CLIENT_ID}
      ODH_AUTH_CLIENT_SECRET: ${ODH_AUTH_CLIENT_SECRET}
    ports:
      - ${SERVER_PORT}:8080
